site_name: "SpartaCyberSecLab Blogs"
site_url: "https://SpartaCyberSecLab.github.io/blogs"
site_description: "SpartaCyberSecLab blogs"
site_author: "SpartaCyberSecLab"
repo_name: 'SpartaCyberSecLab/blogs'
edit_uri: 'blob/master/docs/'
repo_url: 'https://github.com/SpartaCyberSecLab/blogs'


theme:
  name: material
  palete:
    primary: green
    accent: blue
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigating.tabs
    - navigating.sections
    - navigating.top
    - search.suggest
    - search.highlight
  favicon: favicon.png
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - search


nav:
